module.exports = {
    "authorization_index": "/pages/authorization/index",
    "bluetooth_add_index": "/pages/bluetooth/add/index",
    "bluetooth_explain_index": "/pages/bluetooth/explain/index",
    "bluetooth_index": "/pages/bluetooth/index",
    "bluetooth_synchronization_index": "/pages/bluetooth/synchronization/index",
    "bluetooth_transfer_index": "/pages/bluetooth/transfer/index",
    "consult_index": "/pages/consult/index",
    "home_index": "/pages/home/index",
    "mine_index": "/pages/mine/index",
    "mine_info_index": "/pages/mine/info/index",
    "mine_introduce_index": "/pages/mine/introduce/index",
    "mine_month_index": "/pages/mine/month/index",
    "mine_programme_index": "/pages/mine/programme/index",
    "mine_report_index": "/pages/mine/report/index",
    "questionnaire_activation_index": "/pages/questionnaire/activation/index",
    "questionnaire_copy_index": "/pages/questionnaire/copy/index",
    "questionnaire_one_index": "/pages/questionnaire/one/index",
    "questionnaire_programme_index": "/pages/questionnaire/programme/index",
    "questionnaire_three_index": "/pages/questionnaire/three/index",
    "questionnaire_two_index": "/pages/questionnaire/two/index",
    "record_index": "/pages/record/index",
    "result_index": "/pages/result/index",
    "test_index": "/pages/test/index",
    "transition_index": "/pages/transition/index",
    "web_index": "/pages/web/index"
}